function [quad_surfaces_ala, quad_surfaces_fuselaje, warnings] = create_surfaces_ribs_vertical(combined_nodes_3D)
% Creates lines from consecutive rows in a vector_stringer table.
%
% Inputs:
%   vector_stringer   - Table with rows representing nodes in the stringer.
%   stringer_index    - Index of the stringer being processed.
%   tag               - Tag to classify the lines (e.g., 'stringer').
%   h                 - Indicates 'extrados' or 'intrados'.
%   initial_line_counter - Initial line counter value.
%
% Outputs:
%   lines             - Table containing the created lines.
%   line_counter      - Updated line counter after adding all lines.

    %% 📝 Initialize Lines Table
    quad_surfaces_ala = table([], [], [], [], [], [], [], [], [], [], [], [], [], ...
        'VariableNames', {'local_id', 'node_1', 'node_2', 'node_3', 'node_4', ...
                          'stringer_1', 'stringer_2', 'rib_1', 'rib_2', 'tags', ...
                          'area', 'aspect_ratio', 'h'});
    quad_surfaces_fuselaje = table([], [], [], [], [], [], [], [], [], [], [], [], [], ...
        'VariableNames', {'local_id', 'node_1', 'node_2', 'node_3', 'node_4', ...
                          'stringer_1', 'stringer_2', 'rib_1', 'rib_2', 'tags', ...
                          'area', 'aspect_ratio', 'h'});
    warnings = {};
    surface_counter = 1;

    [num_stringers_last_rib, max_rib_index, max_stringer_index, rib_ranges, rib_ranges_by_ribs, special_rib_indices, max_ribs_fuselaje] = analyze_stringer_rib_data_v5(combined_nodes_3D);


%% Creación de las barras verticales en las costillas

% Bucle para las costillas en el ala 
for index_rib = 1:2:max_rib_index

    Vector_extrados = combined_nodes_3D(combined_nodes_3D.rib_index == index_rib & ...
                      combined_nodes_3D.h == 'extrados' & ...
                      combined_nodes_3D.tag == 'stringer' & ...
                      combined_nodes_3D.stringer_index >=  rib_ranges_by_ribs(index_rib, 2) & ...
                      combined_nodes_3D.stringer_index <=  rib_ranges_by_ribs(index_rib, 3) ,:);

    Vector_intrados = combined_nodes_3D(combined_nodes_3D.rib_index == index_rib & ...
                      combined_nodes_3D.h == 'intrados' & ...
                      combined_nodes_3D.tag == 'stringer' & ...
                      combined_nodes_3D.stringer_index >=  rib_ranges_by_ribs(index_rib, 2) & ...
                      combined_nodes_3D.stringer_index <=  rib_ranges_by_ribs(index_rib, 3) ,:);

    nodo_rear_extrados = combined_nodes_3D(combined_nodes_3D.rib_index == index_rib & ...
                         combined_nodes_3D.h == 'extrados' & ...
                         combined_nodes_3D.tag == 'rear spars',:);
    
    nodo_rear_intrados = combined_nodes_3D(combined_nodes_3D.rib_index == index_rib & ...
                         combined_nodes_3D.h == 'intrados' & ...
                         combined_nodes_3D.tag == 'rear spars',:);

    nodo_front_extrados = combined_nodes_3D(combined_nodes_3D.rib_index == index_rib & ...
                          combined_nodes_3D.h == 'extrados' & ...
                          combined_nodes_3D.tag == 'front spars',:);

    nodo_front_intrados = combined_nodes_3D(combined_nodes_3D.rib_index == index_rib & ...
                          combined_nodes_3D.h == 'intrados' & ...
                          combined_nodes_3D.tag == 'front spars',:);

    Vector_extrados = [nodo_rear_extrados; Vector_extrados; nodo_front_extrados];
    Vector_intrados = [nodo_rear_intrados; Vector_intrados; nodo_front_intrados];

    [quad_surfaces_rib, surface_counter] = create_surfaces_from_a_rib_vertical(Vector_extrados, Vector_intrados,...
                                           index_rib, "quad vertical ribs", "vertical", 1);

    quad_surfaces_ala = [quad_surfaces_ala; quad_surfaces_rib];
end


% Bucle para las costillas en el fuselaje
for index_rib = 1:2:max_ribs_fuselaje-1
    
    Vector_extrados = combined_nodes_3D(combined_nodes_3D.rib_index == index_rib & ...
                      combined_nodes_3D.h == 'extrados' & ...
                      combined_nodes_3D.tag == 'stringer fuselaje',:);

    Vector_intrados = combined_nodes_3D(combined_nodes_3D.rib_index == index_rib & ...
                      combined_nodes_3D.h == 'intrados' & ...
                      combined_nodes_3D.tag == 'stringer fuselaje',:);

    nodo_rear_extrados = combined_nodes_3D(combined_nodes_3D.rib_index == index_rib & ...
                         combined_nodes_3D.h == 'extrados' & ...
                         combined_nodes_3D.tag == 'rear spars fuselaje',:);
    
    nodo_rear_intrados = combined_nodes_3D(combined_nodes_3D.rib_index == index_rib & ...
                         combined_nodes_3D.h == 'intrados' & ...
                         combined_nodes_3D.tag == 'rear spars fuselaje',:);

    nodo_front_extrados = combined_nodes_3D(combined_nodes_3D.rib_index == index_rib & ...
                          combined_nodes_3D.h == 'extrados' & ...
                          combined_nodes_3D.tag == 'front spars fuselaje',:);

    nodo_front_intrados = combined_nodes_3D(combined_nodes_3D.rib_index == index_rib & ...
                          combined_nodes_3D.h == 'intrados' & ...
                          combined_nodes_3D.tag == 'front spars fuselaje',:);

    Vector_extrados = [nodo_rear_extrados; Vector_extrados; nodo_front_extrados];
    Vector_intrados = [nodo_rear_intrados; Vector_intrados; nodo_front_intrados];

    [quad_surfaces_rib, surface_counter] = create_surfaces_from_a_rib_vertical(Vector_extrados, Vector_intrados,...
                                           index_rib, "quad vertical ribs fuselaje", "vertical", 1);

    quad_surfaces_fuselaje = [quad_surfaces_fuselaje; quad_surfaces_rib];


end

end
