
% Helper function to find global IDs based on the tag
function [G1, G2, G3, G4] = find_global_quad_ids(current_quad, combined_nodes_3D)
    % FIND_GLOBAL_QUAD_IDS: Determines the Global IDs for G1, G2, G3, and G4 based on the tag.
    %
    % Inputs:
    %   current_quad - Row from the quads table (current quad being processed).
    %   combined_nodes_3D - Table containing node data and their metadata.
    %
    % Outputs:
    %   G1, G2, G3, G4 - Global IDs for the 4 nodes of the quad.

        % Analyze
    [num_stringers_last_rib, max_rib_index, max_stringer_index, rib_ranges, rib_ranges_by_ribs, special_rib_indices, max_ribs_fuselaje] = analyze_stringer_rib_data_v5(combined_nodes_3D);
    

    switch current_quad.tag
        case "quad rear horizontal 2D"

            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == -2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'rear spars' & ...
                                             combined_nodes_3D.h == current_quad.h & ...
                                             combined_nodes_3D.local_id == current_quad.node_1, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h & ...
                                             combined_nodes_3D.local_id == current_quad.node_2, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h & ...
                                             combined_nodes_3D.local_id == current_quad.node_3, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == -2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'rear spars' & ...
                                             combined_nodes_3D.h == current_quad.h & ...
                                             combined_nodes_3D.local_id == current_quad.node_4, :);
        case "quad regular"

            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad irregular surface"

            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h & ...
                                             combined_nodes_3D.local_id == current_quad.node_1, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == -1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'front spars' & ...
                                             combined_nodes_3D.h == current_quad.h & ...
                                             combined_nodes_3D.local_id == current_quad.node_2, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == -1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'front spars' & ...
                                             combined_nodes_3D.h == current_quad.h & ...
                                             combined_nodes_3D.local_id == current_quad.node_3, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h & ...
                                             combined_nodes_3D.local_id == current_quad.node_4, :);
        case "quad irregular P4 inserted"

            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == -2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == 2e5 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
            
        case "quad irregular P1 inserted"
            
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == 2e5 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == -2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == -1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'front spars' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad vertical rear"
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'rear spars'& ...
                                             combined_nodes_3D.h == 'extrados', :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'rear spars'& ...
                                             combined_nodes_3D.h == 'intrados', :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'rear spars'& ...
                                             combined_nodes_3D.h == 'intrados', :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'rear spars'& ...
                                             combined_nodes_3D.h == 'extrados', :);
        case "quad vertical front"
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'front spars'& ...
                                             combined_nodes_3D.h == 'extrados', :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'front spars'& ...
                                             combined_nodes_3D.h == 'intrados', :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'front spars'& ...
                                             combined_nodes_3D.h == 'intrados', :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'front spars'& ...
                                             combined_nodes_3D.h == 'extrados', :);
        case "quad vertical rear fuselaje"
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'rear spars fuselaje'& ...
                                             combined_nodes_3D.h == 'extrados', :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'rear spars fuselaje'& ...
                                             combined_nodes_3D.h == 'intrados', :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'rear spars fuselaje'& ...
                                             combined_nodes_3D.h == 'intrados', :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'rear spars fuselaje'& ...
                                             combined_nodes_3D.h == 'extrados', :);

        case "quad vertical rear fuselaje root"
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'rear spars fuselaje'& ...
                                             combined_nodes_3D.h == 'extrados', :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'rear spars fuselaje'& ...
                                             combined_nodes_3D.h == 'intrados', :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == rib_ranges(1,2) & ...
                                             combined_nodes_3D.tag == 'rear spars' & ...
                                             combined_nodes_3D.h == 'intrados', :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == rib_ranges(1,2) & ...
                                             combined_nodes_3D.tag == 'rear spars' & ...
                                             combined_nodes_3D.h == 'extrados', :);
        case "quad vertical front fuselaje"
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'front spars fuselaje'& ...
                                             combined_nodes_3D.h == 'extrados', :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'front spars fuselaje'& ...
                                             combined_nodes_3D.h == 'intrados', :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'front spars fuselaje'& ...
                                             combined_nodes_3D.h == 'intrados', :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'front spars fuselaje'& ...
                                             combined_nodes_3D.h == 'extrados', :);

        case "quad vertical front fuselaje root"
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'front spars fuselaje'& ...
                                             combined_nodes_3D.h == 'extrados', :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'front spars fuselaje'& ...
                                             combined_nodes_3D.h == 'intrados', :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == 1e5 & ...
                                             combined_nodes_3D.tag == 'front spars' & ...
                                             combined_nodes_3D.h == 'intrados', :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == 1e5 & ...
                                             combined_nodes_3D.tag == 'front spars' & ...
                                             combined_nodes_3D.h == 'extrados', :);
        
        
        case "quad fuselaje rear root"
            
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'rear spars fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == -2 & ...
                                             combined_nodes_3D.rib_index == rib_ranges(1,2) & ...
                                             combined_nodes_3D.tag == 'rear spars' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad fuselaje rear"

            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'rear spars fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'rear spars fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad fuselaje front root"
            
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'front spars fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == 1e5 & ...
                                             combined_nodes_3D.tag == 'front spars' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad fuselaje front"

            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'front spars fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'front spars fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad fuselaje root"
            
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad fuselaje"

            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad irregular root P2 inserted"



            % Extract nodes

            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == -1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == 3e5 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

        case "quad irregular root P3 inserted"

            % Extract nodes
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == -2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'rear spars' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == 3e5 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == -1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

        case "quad irregular root"

            % Extract nodes
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == -1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == -1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad OnlyNode1"

            % Extract nodes
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == 1e5 & ...
                                             combined_nodes_3D.tag == 'front spars' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'front spars' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

        case "quad irregular root corner"
    
            % Extract nodes
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'front spars' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'front spars' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad vertical ribs"
    
            % Extract nodes
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == 'extrados', :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == 'extrados', :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == 'intrados', :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == 'intrados', :);

            if current_quad.stringer_1 == -2
                node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'rear spars' & ...
                                             combined_nodes_3D.h == 'extrados', :);
                node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'rear spars' & ...
                                             combined_nodes_3D.h == 'intrados', :);
            end

            if current_quad.stringer_2 == -1
                node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'front spars' & ...
                                             combined_nodes_3D.h == 'extrados', :);
                node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'front spars' & ...
                                             combined_nodes_3D.h == 'intrados', :);
            end
        case "quad vertical ribs fuselaje"
    
            % Extract nodes
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == 'extrados', :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == 'extrados', :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == 'intrados', :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == 'intrados', :);

            if current_quad.stringer_1 == -2
                node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'rear spars fuselaje' & ...
                                             combined_nodes_3D.h == 'extrados', :);
                node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'rear spars fuselaje' & ...
                                             combined_nodes_3D.h == 'intrados', :);
            end

            if current_quad.stringer_2 == -1
                node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'front spars fuselaje' & ...
                                             combined_nodes_3D.h == 'extrados', :);
                node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'front spars fuselaje' & ...
                                             combined_nodes_3D.h == 'intrados', :);
            end
            
        otherwise
            error('Unknown tag: %s', current_quad.tag);
    end

    % Extract the Global IDs
    if height(node_result1) == 1 && height(node_result2) == 1 && ...
       height(node_result3) == 1 && height(node_result4) == 1
        G1 = node_result1.global_id;
        G2 = node_result2.global_id;
        G3 = node_result3.global_id;
        G4 = node_result4.global_id;
    else
        current_quad
        node_result1
        node_result2
        node_result3
        node_result4
        warning('Ambiguity or missing nodes for quad tag %s. Skipping this quad.', current_quad.tag);
        G1 = NaN; G2 = NaN; G3 = NaN; G4 = NaN;
    end
end
