function nodes_table = convert_nodes_rear_spars_to_table(nodes)
    nodes_table = table( ...
        (1:size(nodes,1))', nodes(:,1), nodes(:,2), ...
        (1:size(nodes,1))', NaN(size(nodes,1),1), ...
        repmat("rear spars", size(nodes,1),1), ...
        'VariableNames', {'local_id', 'x', 'y', 'rib_index', 'stringer_index', 'tag'});
end
