function quads_matrix = process_quads_v1(combined_nodes_3D, quads)
% PROCESS_QUADS_V1: Processes quads (and optionally triangles) to follow the format required by write_bdf_quads,
% ensuring unique global IDs for the nodes of each quad.
%
% Inputs:
%   combined_nodes_3D - Table containing node coordinates and global IDs.
%   quads - Table containing 'local_id', 'node_1', 'node_2', 'node_3', 'node_4', 'tag', 'rib_1',
%           'rib_2', and other metadata.
%
% Output:
%   quads_matrix - Nx8 matrix where each row corresponds to a quad:
%                  [Quad ID (unique), Property ID, G1 (Global ID), G2 (Global ID),
%                   G3 (Global ID), G4 (Global ID), THETA, ZOFFS].

    % Input Validation
    % Mejor tag que tags
    if ~all(ismember({'local_id', 'node_1', 'node_2', 'node_3', 'node_4', 'tags'}, quads.Properties.VariableNames))
        error('The quads table must contain "local_id", "node_1", "node_2", "node_3", "node_4", and "tag" columns.');
    end
    
    % Initialize Result
    num_quads = height(quads);
    quads_matrix = NaN(num_quads, 8); % Preallocate [Quad ID, PID, G1, G2, G3, G4, THETA, ZOFFS]

    global_quad_id = 1; % Initialize unique global Quad ID counter
    processed_count = 0; % Counter for successfully processed quads

    % Loop through each quad
    for i = 1:num_quads
        % Extract the current quad
        current_quad = quads(i, :);

        % Get G1, G2, G3, G4 using the helper function
        [G1, G2, G3, G4] = find_global_quad_ids(current_quad, combined_nodes_3D);

        % Increment the processed quad count and add to the matrix
        processed_count = processed_count + 1;
        quads_matrix(processed_count, :) = [...  % Add to the result matrix
            global_quad_id, ...     % Unique Quad ID
            1, ...                 % Property ID (default to 1)
            G1, ...                % G1 (Global ID)
            G2, ...                % G2 (Global ID)
            G3, ...                % G3 (Global ID)
            G4, ...                % G4 (Global ID)
            0, ...                 % THETA (default to 0)
            0 ...                  % ZOFFS (default to 0)
        ];

        % Increment the unique Quad ID
        global_quad_id = global_quad_id + 1;
    end

    % Step 2: Remove Unprocessed Rows
    quads_matrix = quads_matrix(~any(isnan(quads_matrix), 2), :);

    % Display Summary
    num_unprocessed = num_quads - processed_count;
    if num_unprocessed > 0
        warning('%d quads were not processed and have been removed.', num_unprocessed);
    end

    fprintf('Successfully processed %d quads.\n', processed_count);
end

% Helper function to find global IDs based on the tag
function [G1, G2, G3, G4] = find_global_quad_ids(current_quad, combined_nodes_3D)
    % FIND_GLOBAL_QUAD_IDS: Determines the Global IDs for G1, G2, G3, and G4 based on the tag.
    %
    % Inputs:
    %   current_quad - Row from the quads table (current quad being processed).
    %   combined_nodes_3D - Table containing node data and their metadata.
    %
    % Outputs:
    %   G1, G2, G3, G4 - Global IDs for the 4 nodes of the quad.

        % Analyze
    [num_stringers_last_rib, max_rib_index, max_stringer_index, rib_ranges, rib_ranges_by_ribs, special_rib_indices, max_ribs_fuselaje] = analyze_stringer_rib_data_v4(combined_nodes_3D);
    

    switch current_quad.tags
        case "quad regular"

            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad irregular"

            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == -1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'front spars' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == -1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'front spars' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad irregular P4 inserted"

            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == -2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == 2e5 & ...
                                             combined_nodes_3D.tag == 'inserted' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
            
        case "quad irregular P1 inserted"
            
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == 2e5 & ...
                                             combined_nodes_3D.tag == 'inserted' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == -2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == -1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'front spars' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad rear"

            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == -2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'rear spars' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == -2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'rear spars' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad fuselaje rear root"
            
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'rear spars fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == -2 & ...
                                             combined_nodes_3D.rib_index == rib_ranges(1,2) & ...
                                             combined_nodes_3D.tag == 'rear spars' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad fuselaje rear"

            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'rear spars fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'rear spars fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad fuselaje front root"
            
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'front spars fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == 1e5 & ...
                                             combined_nodes_3D.tag == 'front spars' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad fuselaje front"

            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'front spars fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'front spars fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad fuselaje root"
            
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad fuselaje"

            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer fuselaje' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        case "quad irregular root P2 inserted"
            % Extract nodes

            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == -1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == 3e5 & ...
                                             combined_nodes_3D.tag == 'inserted' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
            

        case "quad irregular root P3 inserted"

            % Extract nodes
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == -2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'rear spars' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == 3e5 & ...
                                             combined_nodes_3D.tag == 'inserted' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == -1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
            current_quad
            node_result1
            node_result2
            node_result3
            node_result4
                % Extract coordinates for surface property calculation
            surface_coords = [
                node_result1.x, node_result1.y;
                node_result2.x, node_result2.y;
                node_result3.x, node_result3.y;
                node_result4.x, node_result4.y
            ];
    
            % Compute area and aspect ratio
            [is_valid, aspect_ratio] = check_aspect_ratio(surface_coords, 'quad')
            area = polyarea(surface_coords(:, 1), surface_coords(:, 2))
        case "quad irregular root"
            % Extract nodes
            node_1 = combined_nodes( ...
                combined_nodes.rib_index == -1 & ...
                combined_nodes.stringer_index == quad_surfaces.stringer_1(i), :); % Bottom-left
            
            node_2 = combined_nodes( ...
                combined_nodes.rib_index == -1 & ...
                combined_nodes.stringer_index == quad_surfaces.stringer_2(i), :); % Bottom-right
            
            node_3 = combined_nodes( ...
                combined_nodes.rib_index == quad_surfaces.rib_2(i) & ...
                combined_nodes.stringer_index == quad_surfaces.stringer_2(i), :); % Top-right
            
            node_4 = combined_nodes( ...
                combined_nodes.rib_index == quad_surfaces.rib_2(i) & ...
                combined_nodes.stringer_index == quad_surfaces.stringer_1(i), :); % Top-left
            % Extract nodes
            node_result1 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == -1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result2 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == -1 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result3 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_2 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);

            node_result4 = combined_nodes_3D(combined_nodes_3D.stringer_index == current_quad.stringer_1 & ...
                                             combined_nodes_3D.rib_index == current_quad.rib_2 & ...
                                             combined_nodes_3D.tag == 'stringer' & ...
                                             combined_nodes_3D.h == current_quad.h, :);
        otherwise
            error('Unknown tag: %s', current_quad.tags);
    end

    % Extract the Global IDs
    if height(node_result1) == 1 && height(node_result2) == 1 && ...
       height(node_result3) == 1 && height(node_result4) == 1
        G1 = node_result1.global_id;
        G2 = node_result2.global_id;
        G3 = node_result3.global_id;
        G4 = node_result4.global_id;
    else
        current_quad
        node_result1
        node_result2
        node_result3
        node_result4
        warning('Ambiguity or missing nodes for quad tag %s. Skipping this quad.', current_quad.tags);
        G1 = NaN; G2 = NaN; G3 = NaN; G4 = NaN;
    end
end
