function lines_matrix = process_lines_v7(combined_nodes_3D, lines)
% PROCESS_LINES_V6: Processes lines to follow the format required by write_bdf_lines,
% ensuring unique global Line IDs with tag-specific logic in the helper function.
%
% Inputs:
%   combined_nodes_3D - Table containing node coordinates and global IDs.
%   lines - Table containing 'local_id', 'node_1', 'node_2', 'tag', 'rib_1', 
%           'rib_2', 'stringer_index', and other metadata.
%
% Output:
%   lines_matrix - Nx4 matrix where each row corresponds to a line:
%                  [Line ID (unique), Property ID, Point1 (Global ID), Point2 (Global ID)]

    % % Input Validation
    % if ~ismember('global_id', combined_nodes_3D.Properties.VariableNames)
    %     error('The combined_nodes_3D table must contain a "global_id" column.');
    % end
    if ~all(ismember({'local_id', 'node_1', 'node_2', 'tag', 'rib_1', 'rib_2', 'stringer_index'}, lines.Properties.VariableNames))
        error('The lines table must contain "local_id", "node_1", "node_2", "tag", "rib_1", "rib_2", and "stringer_index" columns.');
    end

    % Initialize Result
    num_lines = height(lines);
    lines_matrix = NaN(num_lines, 4); % Preallocate [Line ID, Property ID, Point1, Point2]
    
    global_line_id = 1; % Initialize unique global Line ID counter
    processed_count = 0; % Counter for successfully processed lines

    % Inside the loop in process_lines_v6
    for i = 1:num_lines
        % Extract the current line
        current_line = lines(i, :);

        % Get Point1 and Point2 using the helper function
        [Point1, Point2] = find_global_ids(current_line, combined_nodes_3D);

        % Increment the processed line count and add to the matrix
        processed_count = processed_count + 1;
        lines_matrix(processed_count, :) = [...
            global_line_id, ...      % Unique Line ID
            1, ...                  % Property ID (default to 1)
            Point1, ...             % Point1 (Global ID)
            Point2 ...              % Point2 (Global ID)
        ];

        % Increment the unique Line ID
        global_line_id = global_line_id + 1;
        % pause; % Pause execution for debugging
    end

    % Step 2: Remove Unprocessed Rows
    lines_matrix = lines_matrix(~any(isnan(lines_matrix), 2), :);

    % Display Summary
    num_unprocessed = num_lines - processed_count;
    if num_unprocessed > 0
        warning('%d lines were not processed and have been removed.', num_unprocessed);
    end

    fprintf('Successfully processed %d lines.\n', processed_count);
end

% Helper function to find global IDs based on the tag
function [Point1, Point2] = find_global_ids(current_line, combined_nodes_3D)
    % FIND_GLOBAL_IDS: Determines the Global IDs for Point1 and Point2 based on the tag.
    %
    % Inputs:
    %   current_line - Row from the lines table (current line being processed).
    %   node_table - Table containing all nodes and their metadata.
    %
    % Outputs:
    %   Point1, Point2 - Global IDs for the two endpoints of the line.
    switch current_line.tag
        case "stringer fuselaje"
                switch current_line.h
                    case "extrados"
                        node_result1 = combined_nodes_3D( ...
                                            combined_nodes_3D.rib_index == current_line.rib_1 & ...
                                            combined_nodes_3D.h == "extrados" & ...
                                            combined_nodes_3D.stringer_index == current_line.stringer_index & ...
                                            combined_nodes_3D.tag == "stringer fuselaje", :);
                        node_result2 = combined_nodes_3D( ...
                                            combined_nodes_3D.rib_index == current_line.rib_2 & ...
                                            combined_nodes_3D.h == "extrados" & ...
                                            combined_nodes_3D.stringer_index == current_line.stringer_index & ...
                                            combined_nodes_3D.tag == "stringer fuselaje", :);
                    case "intrados"
                        node_result1 = combined_nodes_3D( ...
                                            combined_nodes_3D.rib_index == current_line.rib_1 & ...
                                            combined_nodes_3D.h == "intrados" & ...
                                            combined_nodes_3D.stringer_index == current_line.stringer_index & ...
                                            combined_nodes_3D.tag == "stringer fuselaje", :);
                        node_result2 = combined_nodes_3D( ...
                                            combined_nodes_3D.rib_index == current_line.rib_2 & ...
                                            combined_nodes_3D.h == "intrados" & ...
                                            combined_nodes_3D.stringer_index == current_line.stringer_index & ...
                                            combined_nodes_3D.tag == "stringer fuselaje", :);
                end           

    
        case "stringer"
            switch current_line.h
                case "extrados"
                    node_result1 = combined_nodes_3D( ...
                                        combined_nodes_3D.rib_index == current_line.rib_1 & ...
                                        combined_nodes_3D.h == "extrados" & ...
                                        combined_nodes_3D.stringer_index == current_line.stringer_index & ...
                                        combined_nodes_3D.tag == "stringer", :);
                    node_result2 = combined_nodes_3D( ...
                                        combined_nodes_3D.rib_index == current_line.rib_2 & ...
                                        combined_nodes_3D.h == "extrados" & ...
                                        combined_nodes_3D.stringer_index == current_line.stringer_index & ...
                                        combined_nodes_3D.tag == "stringer", :);
                case "intrados"
                    node_result1 = combined_nodes_3D( ...
                                        combined_nodes_3D.rib_index == current_line.rib_1 & ...
                                        combined_nodes_3D.h == "intrados" & ...
                                        combined_nodes_3D.stringer_index == current_line.stringer_index & ...
                                        combined_nodes_3D.tag == "stringer", :);
                    node_result2 = combined_nodes_3D( ...
                                        combined_nodes_3D.rib_index == current_line.rib_2 & ...
                                        combined_nodes_3D.h == "intrados" & ...
                                        combined_nodes_3D.stringer_index == current_line.stringer_index & ...
                                        combined_nodes_3D.tag == "stringer", :);
            end            
         

        case "rear spar"

            switch current_line.h
                case "extrados"
                    node_result1 = combined_nodes_3D(combined_nodes_3D.tag=='rear spars' & ...
                                      combined_nodes_3D.h == 'extrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_1 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
                    node_result2 = combined_nodes_3D(combined_nodes_3D.tag=='rear spars' & ...
                                      combined_nodes_3D.h == 'extrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_2 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
                case "intrados"
                    node_result1 = combined_nodes_3D(combined_nodes_3D.tag=='rear spars' & ...
                                      combined_nodes_3D.h == 'intrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_1 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
                    node_result2 = combined_nodes_3D(combined_nodes_3D.tag=='rear spars' & ...
                                      combined_nodes_3D.h == 'intrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_2 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
            end
        case "rear spar fuselaje"

            switch current_line.h
                case "extrados"
                    node_result1 = combined_nodes_3D(combined_nodes_3D.tag=='rear spars fuselaje' & ...
                                      combined_nodes_3D.h == 'extrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_1 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
                    node_result2 = combined_nodes_3D(combined_nodes_3D.tag=='rear spars fuselaje' & ...
                                      combined_nodes_3D.h == 'extrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_2 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
                case "intrados"
                    node_result1 = combined_nodes_3D(combined_nodes_3D.tag=='rear spars fuselaje' & ...
                                      combined_nodes_3D.h == 'intrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_1 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
                    node_result2 = combined_nodes_3D(combined_nodes_3D.tag=='rear spars fuselaje' & ...
                                      combined_nodes_3D.h == 'intrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_2 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
            end
        case "front spar"

            switch current_line.h
                case "extrados"
                    node_result1 = combined_nodes_3D(combined_nodes_3D.tag=='front spars' & ...
                                      combined_nodes_3D.h == 'extrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_1 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
                    node_result2 = combined_nodes_3D(combined_nodes_3D.tag=='front spars' & ...
                                      combined_nodes_3D.h == 'extrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_2 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
                case "intrados"
                    node_result1 = combined_nodes_3D(combined_nodes_3D.tag=='front spars' & ...
                                      combined_nodes_3D.h == 'intrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_1 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
                    node_result2 = combined_nodes_3D(combined_nodes_3D.tag=='front spars' & ...
                                      combined_nodes_3D.h == 'intrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_2 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
            end
        case "front spar fuselaje"

            switch current_line.h
                case "extrados"
                    node_result1 = combined_nodes_3D(combined_nodes_3D.tag=='front spars fuselaje' & ...
                                      combined_nodes_3D.h == 'extrados' & ...
                                      combined_nodes_3D.rib_index==current_line.rib_1 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
                    node_result2 = combined_nodes_3D(combined_nodes_3D.tag=='front spars fuselaje' & ...
                                      combined_nodes_3D.h == 'extrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_2 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
                case "intrados"
                    node_result1 = combined_nodes_3D(combined_nodes_3D.tag=='front spars fuselaje' & ...
                                      combined_nodes_3D.h == 'intrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_1 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
                    node_result2 = combined_nodes_3D(combined_nodes_3D.tag=='front spars fuselaje' & ...
                                      combined_nodes_3D.h == 'intrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_2 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
            end
        case "barra costilla"
            % De arriba para abajo el sentido de la barra
                    node_result1 = combined_nodes_3D(combined_nodes_3D.tag=='stringer' & ...
                                      combined_nodes_3D.h == 'extrados' & ...
                                      combined_nodes_3D.rib_index==current_line.rib_1 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
                    node_result2 = combined_nodes_3D(combined_nodes_3D.tag=='stringer' & ...
                                      combined_nodes_3D.h == 'intrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_2 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
            % De arriba para abajo el sentido de la barra
        case "barra costilla fuselaje"
                    node_result1 = combined_nodes_3D(combined_nodes_3D.tag=='stringer fuselaje' & ...
                                      combined_nodes_3D.h == 'extrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_1 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
                    node_result2 = combined_nodes_3D(combined_nodes_3D.tag=='stringer fuselaje' & ...
                                      combined_nodes_3D.h == 'intrados' & ...
                                      combined_nodes_3D.rib_index == current_line.rib_2 & ...
                                      combined_nodes_3D.stringer_index == current_line.stringer_index,:);
        otherwise
            error('Unknown tag: %s', current_line.tag);
    end

    % Check if multiple or zero results are found
    if height(node_result1) ~= 1 || height(node_result2) ~= 1
        % Debugging: Display the current line and combined_nodes_3D being filtered
        disp('Current Line:');
        disp(current_line);
        
        % Check combined_nodes_3D for matches
        debug_result1 = combined_nodes_3D( ...
            combined_nodes_3D.rib_index == current_line{1, 'rib_1'} & ...
            combined_nodes_3D.h == current_line{1, 'h'} & ...
            combined_nodes_3D.stringer_index == current_line{1, 'stringer_index'} & ...
            combined_nodes_3D.tag == current_line{1, 'tag'}, :);
        disp('Matching Node Result 1:');
        disp(debug_result1);
    
        % Repeat for rib_2
        debug_result2 = combined_nodes_3D( ...
            combined_nodes_3D.rib_index == current_line{1, 'rib_2'} & ...
            combined_nodes_3D.h == current_line{1, 'h'} & ...
            combined_nodes_3D.stringer_index == current_line{1, 'stringer_index'} & ...
            combined_nodes_3D.tag == current_line{1, 'tag'}, :);
        disp('Matching Node Result 2:');
        disp(debug_result2);
        warning(['Ambiguity or missing nodes for line local_id %d. Skipping this line.\n' ...
                 'rib_1: %d, rib_2: %d, stringer_index: %d'], ...
                current_line.local_id, current_line.rib_1, ...
                current_line.rib_2, current_line.stringer_index);
    end

    % Assign global IDs to the line
    Point1 = node_result1.global_id;
    Point2 = node_result2.global_id;

end
